name: selenium

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
   push:
   schedule:
     - cron: "0 21 * * *"  # scheduled at 05:00 (UTC+8) everyday #每天早上5点整挂起任务

  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.8
      - name: 'Install requirements'
        run: pip install -r ./spider/requirements.txt


      - name: Download
        run: |
          python ./chrome/GetChromedriver.py
          mv ./chromedriver ./chrome/chromedriver
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "crongenerated"
          git push
